{\rtf1\ansi\ansicpg932\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fnil\fcharset0 Menlo-Bold;\f1\fnil\fcharset0 Menlo-Regular;\f2\fnil\fcharset128 HiraginoSans-W3;
}
{\colortbl;\red255\green255\blue255;\red127\green0\blue85;\red255\green0\blue0;\red255\green0\blue255;
\red0\green0\blue192;\red42\green0\blue255;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\b\fs22 \cf2 import
\f1\b0 \cf0  java.util.Scanner;\

\f0\b \cf2 public
\f1\b0 \cf0  
\f0\b \cf2 class
\f1\b0 \cf0  hello \{\
   
\f0\b \cf2 public
\f1\b0 \cf0  
\f0\b \cf2 static
\f1\b0 \cf0  
\f0\b \cf2 void
\f1\b0 \cf0  main(String[] \cf3 args\cf0 ) \{\
	   Scanner 
\f0\b \cf4 \ul \ulc4 sc
\f1\b0 \cf0 \ulnone  = 
\f0\b \cf2 new
\f1\b0 \cf0  Scanner(System.
\f0\b \cf5 in
\f1\b0 \cf0 );\
	   
\f0\b \cf2 int
\f1\b0 \cf0  
\f0\b \cf4 a
\f1\b0 \cf0  = \cf4 sc\cf0 .nextInt();\
	   
\f0\b \cf2 int
\f1\b0 \cf0  
\f0\b \cf4 b
\f1\b0 \cf0  = \cf4 sc\cf0 .nextInt();\
	   
\f0\b \cf2 if
\f1\b0 \cf0 (\cf4 a\cf0  == \cf4 b\cf0 ) \{\
		   System.
\f0\b \cf5 out
\f1\b0 \cf0 .println(\cf6 "
\f2 \'82\'a0\'82\'a2\'82\'b1
\f1 "\cf0 );\
	   \}
\f0\b \cf2 else
\f1\b0 \cf0 \{\
		   System.
\f0\b \cf5 out
\f1\b0 \cf0 .println(\cf6 "
\f2 \'8f\'9f\'82\'bf
\f1 "\cf0 );\
	   \}\
   \}\
   \}}